services:
  app:
    build: .
    container_name: ${APP_CONTAINER_NAME:-elysia_app}
    restart: always
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-myapp}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - PORT=3000
    depends_on:
      - db
    networks:
      - elysia_net

  db:
    image: postgres:15-alpine
    container_name: ${DB_CONTAINER_NAME:-elysia_db}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-myapp}
    volumes:
      - ${DB_VOLUME_NAME:-postgres_data}:/var/lib/postgresql/data
    networks:
      - elysia_net

  nginx:
    image: nginx:alpine
    container_name: ${NGINX_CONTAINER_NAME:-elysia_nginx}
    restart: always
    ports:
      - '${NGINX_PORT:-80}:80'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - elysia_net

networks:
  elysia_net:
    driver: bridge

volumes:
  postgres_data:
    name: ${DB_VOLUME_NAME:-postgres_data}
